FROM python:3.10-slim

RUN apt-get update && apt-get install -y iptables && \
    pip install kafka-python

WORKDIR /app
COPY responder/responder.py .
COPY responder/config/config.json ./config/config.json

ENTRYPOINT ["python", "responder.py"]