FROM nvidia/cuda:12.2.0-cudnn8-runtime-ubuntu20.04

WORKDIR /app

RUN apt update && apt install -y python3 python3-pip
RUN pip3 install --upgrade pip
RUN pip3 install tensorflow==2.15 scikit-learn pandas joblib

COPY ml_model/train_autoencoder.py .
COPY ml_model/sample_data.csv .

ENTRYPOINT ["python3", "train_autoencoder.py"]